INSERT IGNORE INTO TblQuestion (answer, category, scoringType, text, explanation)
VALUES (21105172, 'TECH', 1,
    'How many questions are there on Stack Overflow',
    'There are approximately 21,105,172 questions on Stack Overflow'),
(700, 'JOKE', 1,
    'How much wood could a wood chuck chuck if a wood chuck could chuck wood',
    'Researchers at Cornell determined that a woodchuck could chuck about 700 pounds'),
(1996, 'TECH', 0,
    'What year was Java released',
    'Java was released in 1996'),
(1912, 'HISTORY', 0,
    'What year was Alan Turing born',
    'Alan Turing was born in 1912'),
(1842, 'HISTORY', 0,
    'When was the first computer program written',
    'Ada Lovelace wrote the first computer program in 1842, an algorithm to calculate some Bernoulli numbers on a Turing complete mechanical computer'),
(1889, 'HISTORY', 0,
    'When was Nintendo founded',
    'Nintendo was founded in 1889 and originally sold hand painted playing cards'),
(38026, 'SPACE', 1,
    'What is the velocity (in mph) of the Voyager 1 space probe',
    'Voyager 1 is traveling at approximately 38,026 mph relative to the sun'),
(54, 'GENERAL', 1,
    'How many people were murdered in Denmark in 2017',
    'There were a total of 54 murders in Denmark in 2017'),
(2560, 'GEOGRAPHY', 1,
    'How many kilometers of railway lines are in Denmark',
    'There are 2560 km of rail in the Danish railway network'),
(250000, 'GEOGRAPHY', 1,
    'How many kilometers of railway lines are in America',
    'There are over 250,000 km of railway lines in America, the largest rail network in the world'),
(7782, 'GEOGRAPHY', 1,
    'How many kilometers apart are Seattle and Copenhagen',
    'Seattle is 7782 km away from Copenhagen'),
(1977, 'HISTORY', 0,
    'When was Oracle Corporation founded',
    'Oracle was founded in 1977'),
(1906, 'HISTORY', 0,
    'When was Xerox founded',
    'Xerox was founded in 1906, manufacturing photographic paper and equipment'),
(40000000, 'TECH', 1,
    'How many users does GitHub have',
    'There are approximately 40,000,000 GitHub users'),
(66, 'SPACE', 0,
    'How many years were between the first airplane flight and the moon landing',
    'There was a gap of only 66 years between the Wright Brothers first flight and the moon landing'),
(1964, 'HISTORY', 0,
    'What year was the computer mouse invented',
    'The first mouse prototype was built in 1964 at the Augmentation Research Center'),
(1950, 'LITERATURE', 0,
    'What year did Isaac Asimov publish "I, Robot"',
    '"I, Robot" was published in 1950'),
(1949, 'LITERATURE', 0,
    'What year did George Orwell publish "1984"',
    '"1984" was published in 1949'),
(1953, 'LITERATURE', 0,
    'What year did Ray Bradbury publish "Fahrenheit 451"',
    '"Fahrenheit 451" was published in 1953'),
(1985, 'LITERATURE', 0,
    'What year did Orson Scott Card publish "Ender\'s Game"',
    '"Ender\'s Game" was published in 1985'),
(1963, 'LITERATURE', 0,
    'What year did Anthony Burgess publish "A Clockwork Orange"',
    '"Fahrenheit 451" was published in 1963'),
(1969, 'HISTORY', 0,
    'When was Linus Torvalds born',
    'Linus Torvalds was born in 1969'),
(1942, 'HISTORY', 0,
    'What year was the first nuclear reactor built',
    'The worlds first nuclear reactor was built in 1942, underneath a football stadium'),
(310, 'GEOGRAPHY', 1,
    'How many cities in America have a population of at least 100,000',
    '310 cities in America have populations of 100,000 or more'),
(1444216107, 'GEOGRAPHY', 1,
    'What is the population of China',
    'China has a population of approximately 1,444,216,107'),
(9706961, 'GEOGRAPHY', 1,
    'What is the area of China in square kilometers',
    'China has an area of 9,706,961'),
(147, 'GEOGRAPHY', 1,
    'What is the population density of China in people/km²',
    'China has a population density of 147 people/km²'),
(1393409038, 'GEOGRAPHY', 1,
    'What is the population of India',
    'India has a population of approximately 1,393,409,038'),
(3287590, 'GEOGRAPHY', 1,
    'What is the area of India in square kilometers',
    'India has an area of 3,287,590'),
(415, 'GEOGRAPHY', 1,
    'What is the population density of India in people/km²',
    'India has a population density of 415 people/km²'),
(332915073, 'GEOGRAPHY', 1,
    'What is the population of United States',
    'United States has a population of approximately 332,915,073'),
(9372610, 'GEOGRAPHY', 1,
    'What is the area of United States in square kilometers',
    'United States has an area of 9,372,610'),
(35, 'GEOGRAPHY', 1,
    'What is the population density of United States in people/km²',
    'United States has a population density of 35 people/km²'),
(145912025, 'GEOGRAPHY', 1,
    'What is the population of Russia',
    'Russia has a population of approximately 145,912,025'),
(17098242, 'GEOGRAPHY', 1,
    'What is the area of Russia in square kilometers',
    'Russia has an area of 17,098,242'),
(8, 'GEOGRAPHY', 1,
    'What is the population density of Russia in people/km²',
    'Russia has a population density of 8 people/km²'),
(130262216, 'GEOGRAPHY', 1,
    'What is the population of Mexico',
    'Mexico has a population of approximately 130,262,216'),
(1964375, 'GEOGRAPHY', 1,
    'What is the area of Mexico in square kilometers',
    'Mexico has an area of 1,964,375'),
(64, 'GEOGRAPHY', 1,
    'What is the population density of Mexico in people/km²',
    'Mexico has a population density of 64 people/km²'),
(126050804, 'GEOGRAPHY', 1,
    'What is the population of Japan',
    'Japan has a population of approximately 126,050,804'),
(377930, 'GEOGRAPHY', 1,
    'What is the area of Japan in square kilometers',
    'Japan has an area of 377,930'),
(335, 'GEOGRAPHY', 1,
    'What is the population density of Japan in people/km²',
    'Japan has a population density of 335 people/km²'),
(104258327, 'GEOGRAPHY', 1,
    'What is the population of Egypt',
    'Egypt has a population of approximately 104,258,327'),
(1002450, 'GEOGRAPHY', 1,
    'What is the area of Egypt in square kilometers',
    'Egypt has an area of 1,002,450'),
(100, 'GEOGRAPHY', 1,
    'What is the population density of Egypt in people/km²',
    'Egypt has a population density of 100 people/km²'),
(83900473, 'GEOGRAPHY', 1,
    'What is the population of Germany',
    'Germany has a population of approximately 83,900,473'),
(357114, 'GEOGRAPHY', 1,
    'What is the area of Germany in square kilometers',
    'Germany has an area of 357,114'),
(233, 'GEOGRAPHY', 1,
    'What is the population density of Germany in people/km²',
    'Germany has a population density of 233 people/km²'),
(68207116, 'GEOGRAPHY', 1,
    'What is the population of United Kingdom',
    'United Kingdom has a population of approximately 68,207,116'),
(242900, 'GEOGRAPHY', 1,
    'What is the area of United Kingdom in square kilometers',
    'United Kingdom has an area of 242,900'),
(278, 'GEOGRAPHY', 1,
    'What is the population density of United Kingdom in people/km²',
    'United Kingdom has a population density of 278 people/km²'),
(65426179, 'GEOGRAPHY', 1,
    'What is the population of France',
    'France has a population of approximately 65,426,179'),
(551695, 'GEOGRAPHY', 1,
    'What is the area of France in square kilometers',
    'France has an area of 551,695'),
(118, 'GEOGRAPHY', 1,
    'What is the population density of France in people/km²',
    'France has a population density of 118 people/km²'),
(60367477, 'GEOGRAPHY', 1,
    'What is the population of Italy',
    'Italy has a population of approximately 60,367,477'),
(301336, 'GEOGRAPHY', 1,
    'What is the area of Italy in square kilometers',
    'Italy has an area of 301,336'),
(200, 'GEOGRAPHY', 1,
    'What is the population density of Italy in people/km²',
    'Italy has a population density of 200 people/km²'),
(46745216, 'GEOGRAPHY', 1,
    'What is the population of Spain',
    'Spain has a population of approximately 46,745,216'),
(505992, 'GEOGRAPHY', 1,
    'What is the area of Spain in square kilometers',
    'Spain has an area of 505,992'),
(92, 'GEOGRAPHY', 1,
    'What is the population density of Spain in people/km²',
    'Spain has a population density of 92 people/km²'),
(38067903, 'GEOGRAPHY', 1,
    'What is the population of Canada',
    'Canada has a population of approximately 38,067,903'),
(9984670, 'GEOGRAPHY', 1,
    'What is the area of Canada in square kilometers',
    'Canada has an area of 9,984,670'),
(3, 'GEOGRAPHY', 1,
    'What is the population density of Canada in people/km²',
    'Canada has a population density of 3 people/km²'),
(37797005, 'GEOGRAPHY', 1,
    'What is the population of Poland',
    'Poland has a population of approximately 37,797,005'),
(312679, 'GEOGRAPHY', 1,
    'What is the area of Poland in square kilometers',
    'Poland has an area of 312,679'),
(121, 'GEOGRAPHY', 1,
    'What is the population density of Poland in people/km²',
    'Poland has a population density of 121 people/km²'),
(25788215, 'GEOGRAPHY', 1,
    'What is the population of Australia',
    'Australia has a population of approximately 25,788,215'),
(7692024, 'GEOGRAPHY', 1,
    'What is the area of Australia in square kilometers',
    'Australia has an area of 7,692,024'),
(3, 'GEOGRAPHY', 1,
    'What is the population density of Australia in people/km²',
    'Australia has a population density of 3 people/km²'),
(17173099, 'GEOGRAPHY', 1,
    'What is the population of Netherlands',
    'Netherlands has a population of approximately 17,173,099'),
(41850, 'GEOGRAPHY', 1,
    'What is the area of Netherlands in square kilometers',
    'Netherlands has an area of 41,850'),
(408, 'GEOGRAPHY', 1,
    'What is the population density of Netherlands in people/km²',
    'Netherlands has a population density of 408 people/km²'),
(11632326, 'GEOGRAPHY', 1,
    'What is the population of Belgium',
    'Belgium has a population of approximately 11,632,326'),
(30528, 'GEOGRAPHY', 1,
    'What is the area of Belgium in square kilometers',
    'Belgium has an area of 30,528'),
(377, 'GEOGRAPHY', 1,
    'What is the population density of Belgium in people/km²',
    'Belgium has a population density of 377 people/km²'),
(10167925, 'GEOGRAPHY', 1,
    'What is the population of Portugal',
    'Portugal has a population of approximately 10,167,925'),
(92090, 'GEOGRAPHY', 1,
    'What is the area of Portugal in square kilometers',
    'Portugal has an area of 92,090'),
(111, 'GEOGRAPHY', 1,
    'What is the population density of Portugal in people/km²',
    'Portugal has a population density of 111 people/km²'),
(10160169, 'GEOGRAPHY', 1,
    'What is the population of Sweden',
    'Sweden has a population of approximately 10,160,169'),
(450295, 'GEOGRAPHY', 1,
    'What is the area of Sweden in square kilometers',
    'Sweden has an area of 450,295'),
(22, 'GEOGRAPHY', 1,
    'What is the population density of Sweden in people/km²',
    'Sweden has a population density of 22 people/km²'),
(8715494.0, 'GEOGRAPHY', 1,
    'What is the population of Switzerland',
    'Switzerland has a population of approximately 8,715,494'),
(41284, 'GEOGRAPHY', 1,
    'What is the area of Switzerland in square kilometers',
    'Switzerland has an area of 41,284'),
(208, 'GEOGRAPHY', 1,
    'What is the population density of Switzerland in people/km²',
    'Switzerland has a population density of 208 people/km²'),
(5813298.0, 'GEOGRAPHY', 1,
    'What is the population of Denmark',
    'Denmark has a population of approximately 5,813,298'),
(43094, 'GEOGRAPHY', 1,
    'What is the area of Denmark in square kilometers',
    'Denmark has an area of 43,094'),
(133, 'GEOGRAPHY', 1,
    'What is the population density of Denmark in people/km²',
    'Denmark has a population density of 133 people/km²'),
(5548360.0, 'GEOGRAPHY', 1,
    'What is the population of Finland',
    'Finland has a population of approximately 5,548,360'),
(338424, 'GEOGRAPHY', 1,
    'What is the area of Finland in square kilometers',
    'Finland has an area of 338,424'),
(16, 'GEOGRAPHY', 1,
    'What is the population density of Finland in people/km²',
    'Finland has a population density of 16 people/km²'),
(5465630.0, 'GEOGRAPHY', 1,
    'What is the population of Norway',
    'Norway has a population of approximately 5,465,630'),
(323802, 'GEOGRAPHY', 1,
    'What is the area of Norway in square kilometers',
    'Norway has an area of 323,802'),
(16, 'GEOGRAPHY', 1,
    'What is the population density of Norway in people/km²',
    'Norway has a population density of 16 people/km²'),
(4982907.0, 'GEOGRAPHY', 1,
    'What is the population of Ireland',
    'Ireland has a population of approximately 4,982,907'),
(70273, 'GEOGRAPHY', 1,
    'What is the area of Ireland in square kilometers',
    'Ireland has an area of 70,273'),
(69, 'GEOGRAPHY', 1,
    'What is the population density of Ireland in people/km²',
    'Ireland has a population density of 69 people/km²'),
(4860643.0, 'GEOGRAPHY', 1,
    'What is the population of New Zealand',
    'New Zealand has a population of approximately 4,860,643'),
(270467, 'GEOGRAPHY', 1,
    'What is the area of New Zealand in square kilometers',
    'New Zealand has an area of 270,467'),
(17, 'GEOGRAPHY', 1,
    'What is the population density of New Zealand in people/km²',
    'New Zealand has a population density of 17 people/km²'),
(343353.0, 'GEOGRAPHY', 1,
    'What is the population of Iceland',
    'Iceland has a population of approximately 343,353'),
(103000, 'GEOGRAPHY', 1,
    'What is the area of Iceland in square kilometers',
    'Iceland has an area of 103,000'),
(3, 'GEOGRAPHY', 1,
    'What is the population density of Iceland in people/km²',
    'Iceland has a population density of 3 people/km²'),
(10800, 'HISTORY', 1,
    'How many pounds did the plutonium bomb known as Fat Man weigh',
    'Fat Man weighed 10,800 pounds')
;